export interface Circuit {
  id: string
  name: string
  country: string
  countryCode: string
  city: string
  length: string
  turns: number
  lapRecord: {
    time: string
    driver: string
    year: number
  }
  firstGrandPrix: number
  coordinates: {
    x: number // percentage position on the map (0-100)
    y: number // percentage position on the map (0-100)
  }
  description: string
  image: string
  history?: {
    year: number
    winner: string
    team: string
    laps: number
    time: string
  }[]
  features?: {
    drsZones: number
    fastestCorner: string
    slowestCorner: string
    longestStraight: string
    pitLaneLength: string
    lapDistance: string
    raceDistance: string
  }
}

export const circuits: Circuit[] = [
  {
    id: "bahrain",
    name: "Bahrain International Circuit",
    country: "Bahrain",
    countryCode: "bh",
    city: "Sakhir",
    length: "5.412 km",
    turns: 15,
    lapRecord: {
      time: "1:31.447",
      driver: "Pedro de la Rosa",
      year: 2005,
    },
    firstGrandPrix: 2004,
    coordinates: {
      x: 56.5,
      y: 42.5,
    },
    description:
      "The Bahrain International Circuit is a motorsport venue opened in 2004 and used for drag racing, GP2, and the annual Bahrain Grand Prix. The first Bahrain Grand Prix was held on April 4, 2004.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 57,
        time: "1:33:56.736",
      },
      {
        year: 2022,
        winner: "Charles Leclerc",
        team: "Ferrari",
        laps: 57,
        time: "1:37:33.584",
      },
      {
        year: 2021,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 56,
        time: "1:32:03.897",
      },
      {
        year: 2020,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 57,
        time: "1:34:01.829",
      },
      {
        year: 2019,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 57,
        time: "1:34:21.295",
      },
    ],
    features: {
      drsZones: 3,
      fastestCorner: "Turn 12 (240 km/h)",
      slowestCorner: "Turn 10 (65 km/h)",
      longestStraight: "1.2 km",
      pitLaneLength: "420 m",
      lapDistance: "5.412 km",
      raceDistance: "308.238 km (57 laps)",
    },
  },
  {
    id: "jeddah",
    name: "Jeddah Corniche Circuit",
    country: "Saudi Arabia",
    countryCode: "sa",
    city: "Jeddah",
    length: "6.174 km",
    turns: 27,
    lapRecord: {
      time: "1:30.734",
      driver: "Lewis Hamilton",
      year: 2021,
    },
    firstGrandPrix: 2021,
    coordinates: {
      x: 54.5,
      y: 43.5,
    },
    description:
      "The Jeddah Corniche Circuit is a street circuit in Jeddah, Saudi Arabia. It was constructed to host the inaugural Saudi Arabian Grand Prix in 2021. It is the second-longest circuit on the current Formula One calendar.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Sergio Perez",
        team: "Red Bull Racing",
        laps: 50,
        time: "1:21:14.894",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 50,
        time: "1:24:19.293",
      },
      {
        year: 2021,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 50,
        time: "2:06:15.118",
      },
    ],
    features: {
      drsZones: 3,
      fastestCorner: "Turn 10 (270 km/h)",
      slowestCorner: "Turn 1 (80 km/h)",
      longestStraight: "1.2 km",
      pitLaneLength: "380 m",
      lapDistance: "6.174 km",
      raceDistance: "308.45 km (50 laps)",
    },
  },
  {
    id: "albert-park",
    name: "Albert Park Circuit",
    country: "Australia",
    countryCode: "au",
    city: "Melbourne",
    length: "5.278 km",
    turns: 14,
    lapRecord: {
      time: "1:20.260",
      driver: "Charles Leclerc",
      year: 2022,
    },
    firstGrandPrix: 1996,
    coordinates: {
      x: 84.5,
      y: 68.5,
    },
    description:
      "The Albert Park Circuit is a street circuit around Albert Park Lake, south of central Melbourne. It is used annually as a racetrack for the Formula One Australian Grand Prix and associated support races.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 58,
        time: "1:32:38.371",
      },
      {
        year: 2022,
        winner: "Charles Leclerc",
        team: "Ferrari",
        laps: 58,
        time: "1:27:46.548",
      },
      {
        year: 2019,
        winner: "Valtteri Bottas",
        team: "Mercedes",
        laps: 58,
        time: "1:25:27.325",
      },
      {
        year: 2018,
        winner: "Sebastian Vettel",
        team: "Ferrari",
        laps: 58,
        time: "1:29:33.283",
      },
      {
        year: 2017,
        winner: "Sebastian Vettel",
        team: "Ferrari",
        laps: 57,
        time: "1:24:11.672",
      },
    ],
    features: {
      drsZones: 4,
      fastestCorner: "Turn 8 (225 km/h)",
      slowestCorner: "Turn 3 (90 km/h)",
      longestStraight: "0.86 km",
      pitLaneLength: "280 m",
      lapDistance: "5.278 km",
      raceDistance: "306.124 km (58 laps)",
    },
  },
  {
    id: "suzuka",
    name: "Suzuka International Racing Course",
    country: "Japan",
    countryCode: "jp",
    city: "Suzuka",
    length: "5.807 km",
    turns: 18,
    lapRecord: {
      time: "1:30.983",
      driver: "Lewis Hamilton",
      year: 2019,
    },
    firstGrandPrix: 1987,
    coordinates: {
      x: 85.5,
      y: 39.5,
    },
    description:
      "The Suzuka International Racing Course is a motorsport race track located in Ino, Suzuka City, Mie Prefecture, Japan. It has a unique figure-eight layout with a long 1.2 km back straight that passes over the front section by means of an overpass.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 53,
        time: "1:30:58.094",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 53,
        time: "1:32:23.873",
      },
      {
        year: 2019,
        winner: "Valtteri Bottas",
        team: "Mercedes",
        laps: 53,
        time: "1:21:46.755",
      },
      {
        year: 2018,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 53,
        time: "1:27:30.071",
      },
      {
        year: 2017,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 53,
        time: "1:27:31.194",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "130R (300 km/h)",
      slowestCorner: "Hairpin (60 km/h)",
      longestStraight: "1.2 km",
      pitLaneLength: "350 m",
      lapDistance: "5.807 km",
      raceDistance: "307.471 km (53 laps)",
    },
  },
  {
    id: "shanghai",
    name: "Shanghai International Circuit",
    country: "China",
    countryCode: "cn",
    city: "Shanghai",
    length: "5.451 km",
    turns: 16,
    lapRecord: {
      time: "1:32.238",
      driver: "Michael Schumacher",
      year: 2004,
    },
    firstGrandPrix: 2004,
    coordinates: {
      x: 79.5,
      y: 41.5,
    },
    description:
      "The Shanghai International Circuit is a motorsport race track in the Jiading District, Shanghai. The circuit was designed as the race course for the Formula One Chinese Grand Prix and is shaped like the Chinese character 'shang' which stands for 'high' or 'above'.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2019,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 56,
        time: "1:32:06.350",
      },
      {
        year: 2018,
        winner: "Daniel Ricciardo",
        team: "Red Bull Racing",
        laps: 56,
        time: "1:41:53.762",
      },
      {
        year: 2017,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 56,
        time: "1:37:36.158",
      },
      {
        year: 2016,
        winner: "Nico Rosberg",
        team: "Mercedes",
        laps: 56,
        time: "1:38:53.891",
      },
      {
        year: 2015,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 56,
        time: "1:39:42.008",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Turn 1 (280 km/h)",
      slowestCorner: "Turn 14 (80 km/h)",
      longestStraight: "1.17 km",
      pitLaneLength: "400 m",
      lapDistance: "5.451 km",
      raceDistance: "305.066 km (56 laps)",
    },
  },
  {
    id: "miami",
    name: "Miami International Autodrome",
    country: "United States",
    countryCode: "us",
    city: "Miami",
    length: "5.412 km",
    turns: 19,
    lapRecord: {
      time: "1:31.361",
      driver: "Max Verstappen",
      year: 2022,
    },
    firstGrandPrix: 2022,
    coordinates: {
      x: 25.5,
      y: 42.5,
    },
    description:
      "The Miami International Autodrome is a temporary circuit around Hard Rock Stadium in Miami Gardens, Florida. It was constructed to host the Miami Grand Prix, which was first held in 2022.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 57,
        time: "1:27:38.241",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 57,
        time: "1:34:24.258",
      },
    ],
    features: {
      drsZones: 3,
      fastestCorner: "Turn 4 (257 km/h)",
      slowestCorner: "Turn 11 (72 km/h)",
      longestStraight: "1.28 km",
      pitLaneLength: "360 m",
      lapDistance: "5.412 km",
      raceDistance: "308.326 km (57 laps)",
    },
  },
  {
    id: "imola",
    name: "Autodromo Enzo e Dino Ferrari",
    country: "Italy",
    countryCode: "it",
    city: "Imola",
    length: "4.909 km",
    turns: 19,
    lapRecord: {
      time: "1:15.484",
      driver: "Lewis Hamilton",
      year: 2020,
    },
    firstGrandPrix: 1980,
    coordinates: {
      x: 48.5,
      y: 37.5,
    },
    description:
      "The Autodromo Internazionale Enzo e Dino Ferrari, better known as Imola, is a motor racing circuit in the town of Imola, near Bologna. It is named after Ferrari's founder, Enzo Ferrari, and his son, Dino, who died in 1956.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 63,
        time: "1:32:07.986",
      },
      {
        year: 2021,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 63,
        time: "2:02:34.598",
      },
      {
        year: 2020,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 63,
        time: "1:28:32.430",
      },
      {
        year: 2006,
        winner: "Michael Schumacher",
        team: "Ferrari",
        laps: 62,
        time: "1:31:06.486",
      },
      {
        year: 2005,
        winner: "Fernando Alonso",
        team: "Renault",
        laps: 62,
        time: "1:27:41.921",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Turn 13 (260 km/h)",
      slowestCorner: "Turn 7 (90 km/h)",
      longestStraight: "0.7 km",
      pitLaneLength: "300 m",
      lapDistance: "4.909 km",
      raceDistance: "309.049 km (63 laps)",
    },
  },
  {
    id: "monaco",
    name: "Circuit de Monaco",
    country: "Monaco",
    countryCode: "mc",
    city: "Monte Carlo",
    length: "3.337 km",
    turns: 19,
    lapRecord: {
      time: "1:12.909",
      driver: "Lewis Hamilton",
      year: 2021,
    },
    firstGrandPrix: 1950,
    coordinates: {
      x: 47.5,
      y: 37.5,
    },
    description:
      "The Circuit de Monaco is a street circuit laid out on the city streets of Monte Carlo and La Condamine around the harbor of the Principality of Monaco. It is commonly referred to as 'Monte Carlo' because it is largely inside the Monte Carlo neighborhood of Monaco.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 78,
        time: "1:48:51.980",
      },
      {
        year: 2022,
        winner: "Sergio Perez",
        team: "Red Bull Racing",
        laps: 64,
        time: "1:56:30.265",
      },
      {
        year: 2021,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 78,
        time: "1:38:56.820",
      },
      {
        year: 2019,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 78,
        time: "1:43:09.095",
      },
      {
        year: 2018,
        winner: "Daniel Ricciardo",
        team: "Red Bull Racing",
        laps: 78,
        time: "1:42:54.807",
      },
    ],
    features: {
      drsZones: 1,
      fastestCorner: "Turn 3 (160 km/h)",
      slowestCorner: "Fairmont Hairpin (50 km/h)",
      longestStraight: "0.51 km",
      pitLaneLength: "250 m",
      lapDistance: "3.337 km",
      raceDistance: "260.286 km (78 laps)",
    },
  },
  {
    id: "montreal",
    name: "Circuit Gilles Villeneuve",
    country: "Canada",
    countryCode: "ca",
    city: "Montreal",
    length: "4.361 km",
    turns: 14,
    lapRecord: {
      time: "1:13.078",
      driver: "Valtteri Bottas",
      year: 2019,
    },
    firstGrandPrix: 1978,
    coordinates: {
      x: 27.5,
      y: 36.5,
    },
    description:
      "The Circuit Gilles Villeneuve is a motor racing circuit in Montreal, Quebec, Canada. It is the venue for the Formula One Canadian Grand Prix. It is named after Canadian Formula One driver Gilles Villeneuve, father of Jacques Villeneuve.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 70,
        time: "1:33:58.348",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 70,
        time: "1:36:21.757",
      },
      {
        year: 2019,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 70,
        time: "1:29:07.084",
      },
      {
        year: 2018,
        winner: "Sebastian Vettel",
        team: "Ferrari",
        laps: 68,
        time: "1:28:31.377",
      },
      {
        year: 2017,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 70,
        time: "1:33:05.688",
      },
    ],
    features: {
      drsZones: 3,
      fastestCorner: "Turn 1 (240 km/h)",
      slowestCorner: "Turn 10 (70 km/h)",
      longestStraight: "1.06 km",
      pitLaneLength: "320 m",
      lapDistance: "4.361 km",
      raceDistance: "305.27 km (70 laps)",
    },
  },
  {
    id: "barcelona",
    name: "Circuit de Barcelona-Catalunya",
    country: "Spain",
    countryCode: "es",
    city: "Barcelona",
    length: "4.675 km",
    turns: 16,
    lapRecord: {
      time: "1:18.149",
      driver: "Max Verstappen",
      year: 2021,
    },
    firstGrandPrix: 1991,
    coordinates: {
      x: 45.5,
      y: 38.5,
    },
    description:
      "The Circuit de Barcelona-Catalunya is a motorsport race track in Montmeló, Catalonia, Spain. The track has been the home of the Formula One Spanish Grand Prix since 1991 and also hosts the Catalan motorcycle Grand Prix.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 66,
        time: "1:27:57.940",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 66,
        time: "1:37:20.475",
      },
      {
        year: 2021,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 66,
        time: "1:28:10.642",
      },
      {
        year: 2020,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 66,
        time: "1:31:45.279",
      },
      {
        year: 2019,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 66,
        time: "1:35:50.443",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Turn 9 (250 km/h)",
      slowestCorner: "Turn 10 (70 km/h)",
      longestStraight: "1.05 km",
      pitLaneLength: "410 m",
      lapDistance: "4.675 km",
      raceDistance: "307.236 km (66 laps)",
    },
  },
  {
    id: "spielberg",
    name: "Red Bull Ring",
    country: "Austria",
    countryCode: "at",
    city: "Spielberg",
    length: "4.318 km",
    turns: 10,
    lapRecord: {
      time: "1:05.619",
      driver: "Carlos Sainz",
      year: 2020,
    },
    firstGrandPrix: 1970,
    coordinates: {
      x: 49.5,
      y: 36.5,
    },
    description:
      "The Red Bull Ring is a motorsport race track in Spielberg, Styria, Austria. It was founded as Österreichring and later named A1-Ring before being renamed to its current name in 2011 when Red Bull purchased and renovated the circuit.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 71,
        time: "1:25:33.607",
      },
      {
        year: 2022,
        winner: "Charles Leclerc",
        team: "Ferrari",
        laps: 71,
        time: "1:24:24.312",
      },
      {
        year: 2021,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 71,
        time: "1:23:54.543",
      },
      {
        year: 2020,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 71,
        time: "1:22:50.683",
      },
      {
        year: 2019,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 71,
        time: "1:22:01.822",
      },
    ],
    features: {
      drsZones: 3,
      fastestCorner: "Turn 9 (240 km/h)",
      slowestCorner: "Turn 3 (85 km/h)",
      longestStraight: "0.85 km",
      pitLaneLength: "270 m",
      lapDistance: "4.318 km",
      raceDistance: "306.452 km (71 laps)",
    },
  },
  {
    id: "silverstone",
    name: "Silverstone Circuit",
    country: "United Kingdom",
    countryCode: "gb",
    city: "Silverstone",
    length: "5.891 km",
    turns: 18,
    lapRecord: {
      time: "1:27.097",
      driver: "Max Verstappen",
      year: 2020,
    },
    firstGrandPrix: 1950,
    coordinates: {
      x: 45.5,
      y: 34.5,
    },
    description:
      "The Silverstone Circuit is a motor racing circuit in England, near the Northamptonshire villages of Silverstone and Whittlebury. It is the current home of the British Grand Prix, which it first hosted in 1948.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 52,
        time: "1:25:16.938",
      },
      {
        year: 2022,
        winner: "Carlos Sainz Jr.",
        team: "Ferrari",
        laps: 52,
        time: "1:21:31.611",
      },
      {
        year: 2021,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 52,
        time: "1:58:23.284",
      },
      {
        year: 2020,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 52,
        time: "1:28:01.283",
      },
      {
        year: 2019,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 52,
        time: "1:24:28.739",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Maggots and Becketts (290 km/h)",
      slowestCorner: "Vale (80 km/h)",
      longestStraight: "0.77 km",
      pitLaneLength: "480 m",
      lapDistance: "5.891 km",
      raceDistance: "306.198 km (52 laps)",
    },
  },
  {
    id: "hungaroring",
    name: "Hungaroring",
    country: "Hungary",
    countryCode: "hu",
    city: "Mogyoród",
    length: "4.381 km",
    turns: 14,
    lapRecord: {
      time: "1:16.627",
      driver: "Lewis Hamilton",
      year: 2020,
    },
    firstGrandPrix: 1986,
    coordinates: {
      x: 51.5,
      y: 35.5,
    },
    description:
      "The Hungaroring is a motorsport race track in Mogyoród, Hungary where the Formula One Hungarian Grand Prix is held. It was the first Formula One race to be held behind the Iron Curtain in 1986.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 70,
        time: "1:38:08.634",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 70,
        time: "1:39:35.912",
      },
      {
        year: 2021,
        winner: "Esteban Ocon",
        team: "Alpine",
        laps: 70,
        time: "2:04:43.199",
      },
      {
        year: 2020,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 70,
        time: "1:36:12.473",
      },
      {
        year: 2019,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 70,
        time: "1:35:03.796",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Turn 4 (200 km/h)",
      slowestCorner: "Turn 6 (70 km/h)",
      longestStraight: "0.79 km",
      pitLaneLength: "380 m",
      lapDistance: "4.381 km",
      raceDistance: "306.63 km (70 laps)",
    },
  },
  {
    id: "spa",
    name: "Circuit de Spa-Francorchamps",
    country: "Belgium",
    countryCode: "be",
    city: "Stavelot",
    length: "7.004 km",
    turns: 19,
    lapRecord: {
      time: "1:46.286",
      driver: "Valtteri Bottas",
      year: 2018,
    },
    firstGrandPrix: 1950,
    coordinates: {
      x: 47.5,
      y: 34.5,
    },
    description:
      "The Circuit de Spa-Francorchamps is a motor-racing circuit located in Stavelot, Belgium. It is the venue of the Formula One Belgian Grand Prix and is known for its challenging fast corners, dramatic elevation changes, and beautiful forest setting.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 44,
        time: "1:22:30.450",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 44,
        time: "1:25:52.494",
      },
      {
        year: 2021,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 3,
        time: "0:03:27.071",
      },
      {
        year: 2019,
        winner: "Charles Leclerc",
        team: "Ferrari",
        laps: 44,
        time: "1:26:15.486",
      },
      {
        year: 2018,
        winner: "Sebastian Vettel",
        team: "Ferrari",
        laps: 44,
        time: "1:23:34.476",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Eau Rouge (300 km/h)",
      slowestCorner: "La Source (75 km/h)",
      longestStraight: "2.0 km",
      pitLaneLength: "400 m",
      lapDistance: "7.004 km",
      raceDistance: "308.052 km (44 laps)",
    },
  },
  {
    id: "zandvoort",
    name: "Circuit Zandvoort",
    country: "Netherlands",
    countryCode: "nl",
    city: "Zandvoort",
    length: "4.259 km",
    turns: 14,
    lapRecord: {
      time: "1:11.097",
      driver: "Lewis Hamilton",
      year: 2021,
    },
    firstGrandPrix: 1952,
    coordinates: {
      x: 47.5,
      y: 33.5,
    },
    description:
      "Circuit Zandvoort is a motorsport race track located in the dunes north of Zandvoort, Netherlands. It is the venue for the Formula One Dutch Grand Prix, which returned to the Formula One calendar in 2021 after a 36-year absence.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 72,
        time: "1:22:30.450",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 72,
        time: "1:36:42.773",
      },
      {
        year: 2021,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 72,
        time: "1:30:05.395",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Turn 7 (250 km/h)",
      slowestCorner: "Turn 11 (80 km/h)",
      longestStraight: "0.7 km",
      pitLaneLength: "300 m",
      lapDistance: "4.259 km",
      raceDistance: "306.648 km (72 laps)",
    },
  },
  {
    id: "monza",
    name: "Autodromo Nazionale di Monza",
    country: "Italy",
    countryCode: "it",
    city: "Monza",
    length: "5.793 km",
    turns: 11,
    lapRecord: {
      time: "1:21.046",
      driver: "Rubens Barrichello",
      year: 2004,
    },
    firstGrandPrix: 1950,
    coordinates: {
      x: 48.5,
      y: 36.5,
    },
    description:
      "The Autodromo Nazionale di Monza is a historic race track located near the city of Monza, north of Milan, in Italy. Built in 1922, it is the world's third purpose-built motor racing circuit and the oldest in mainland Europe.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 51,
        time: "1:13:41.446",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 53,
        time: "1:20:27.511",
      },
      {
        year: 2021,
        winner: "Daniel Ricciardo",
        team: "McLaren",
        laps: 53,
        time: "1:12:51.717",
      },
      {
        year: 2020,
        winner: "Pierre Gasly",
        team: "AlphaTauri",
        laps: 53,
        time: "1:47:06.634",
      },
      {
        year: 2019,
        winner: "Charles Leclerc",
        team: "Ferrari",
        laps: 53,
        time: "1:15:18.114",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Curva Grande (340 km/h)",
      slowestCorner: "Variante Ascari (85 km/h)",
      longestStraight: "1.12 km",
      pitLaneLength: "360 m",
      lapDistance: "5.793 km",
      raceDistance: "307.029 km (53 laps)",
    },
  },
  {
    id: "baku",
    name: "Baku City Circuit",
    country: "Azerbaijan",
    countryCode: "az",
    city: "Baku",
    length: "6.003 km",
    turns: 20,
    lapRecord: {
      time: "1:43.009",
      driver: "Charles Leclerc",
      year: 2019,
    },
    firstGrandPrix: 2016,
    coordinates: {
      x: 58.5,
      y: 37.5,
    },
    description:
      "The Baku City Circuit is a street circuit in Baku, Azerbaijan. It is the venue for the Azerbaijan Grand Prix. The track is 6.003 km (3.730 mi) long and features the characteristics of a street circuit with its narrow sections.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Sergio Perez",
        team: "Red Bull Racing",
        laps: 51,
        time: "1:32:42.426",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 51,
        time: "1:28:06.757",
      },
      {
        year: 2021,
        winner: "Sergio Perez",
        team: "Red Bull Racing",
        laps: 51,
        time: "2:13:36.410",
      },
      {
        year: 2019,
        winner: "Valtteri Bottas",
        team: "Mercedes",
        laps: 51,
        time: "1:31:52.001",
      },
      {
        year: 2018,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 51,
        time: "1:43:05.094",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Turn 5 (290 km/h)",
      slowestCorner: "Turn 8 (70 km/h)",
      longestStraight: "2.2 km",
      pitLaneLength: "310 m",
      lapDistance: "6.003 km",
      raceDistance: "306.183 km (51 laps)",
    },
  },
  {
    id: "singapore",
    name: "Marina Bay Street Circuit",
    country: "Singapore",
    countryCode: "sg",
    city: "Singapore",
    length: "4.940 km",
    turns: 19,
    lapRecord: {
      time: "1:41.905",
      driver: "Kevin Magnussen",
      year: 2018,
    },
    firstGrandPrix: 2008,
    coordinates: {
      x: 75.5,
      y: 51.5,
    },
    description:
      "The Marina Bay Street Circuit is a street circuit around Marina Bay in Singapore. It is the venue for the Singapore Grand Prix. The track is 5.063 km (3.146 mi) long and features 19 corners. It was the first night race in Formula One history.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Carlos Sainz Jr.",
        team: "Ferrari",
        laps: 62,
        time: "2:01:53.552",
      },
      {
        year: 2022,
        winner: "Sergio Perez",
        team: "Red Bull Racing",
        laps: 59,
        time: "2:02:15.238",
      },
      {
        year: 2019,
        winner: "Sebastian Vettel",
        team: "Ferrari",
        laps: 61,
        time: "1:58:33.667",
      },
      {
        year: 2018,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 61,
        time: "1:51:11.611",
      },
      {
        year: 2017,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 58,
        time: "2:03:23.544",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Turn 7 (180 km/h)",
      slowestCorner: "Turn 18 (75 km/h)",
      longestStraight: "0.74 km",
      pitLaneLength: "340 m",
      lapDistance: "4.940 km",
      raceDistance: "306.143 km (62 laps)",
    },
  },
  {
    id: "austin",
    name: "Circuit of the Americas",
    country: "United States",
    countryCode: "us",
    city: "Austin",
    length: "5.513 km",
    turns: 20,
    lapRecord: {
      time: "1:36.169",
      driver: "Charles Leclerc",
      year: 2019,
    },
    firstGrandPrix: 2012,
    coordinates: {
      x: 22.5,
      y: 42.5,
    },
    description:
      "The Circuit of the Americas is a grade 1 FIA-specification motorsport race track in Austin, Texas. It is the first purpose-built Formula One facility in the United States designed for any and all classes of racing.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 56,
        time: "1:28:18.824",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 56,
        time: "1:42:11.686",
      },
      {
        year: 2021,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 56,
        time: "1:34:36.552",
      },
      {
        year: 2019,
        winner: "Valtteri Bottas",
        team: "Mercedes",
        laps: 56,
        time: "1:33:55.653",
      },
      {
        year: 2018,
        winner: "Kimi Räikkönen",
        team: "Ferrari",
        laps: 56,
        time: "1:34:18.643",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Turn 1 (270 km/h)",
      slowestCorner: "Turn 11 (80 km/h)",
      longestStraight: "1.2 km",
      pitLaneLength: "380 m",
      lapDistance: "5.513 km",
      raceDistance: "308.405 km (56 laps)",
    },
  },
  {
    id: "mexico-city",
    name: "Autódromo Hermanos Rodríguez",
    country: "Mexico",
    countryCode: "mx",
    city: "Mexico City",
    length: "4.304 km",
    turns: 17,
    lapRecord: {
      time: "1:17.774",
      driver: "Valtteri Bottas",
      year: 2021,
    },
    firstGrandPrix: 1963,
    coordinates: {
      x: 21.5,
      y: 45.5,
    },
    description:
      "The Autódromo Hermanos Rodríguez is a motorsport race track in Mexico City, Mexico. Named after the racing drivers Ricardo and Pedro Rodríguez, it is the main Mexican motorsport venue and hosts the Formula One Mexican Grand Prix.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 71,
        time: "1:32:30.992",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 71,
        time: "1:38:36.729",
      },
      {
        year: 2021,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 71,
        time: "1:25:02.732",
      },
      {
        year: 2019,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 71,
        time: "1:36:48.904",
      },
      {
        year: 2018,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 71,
        time: "1:38:28.851",
      },
    ],
    features: {
      drsZones: 3,
      fastestCorner: "Turn 1 (260 km/h)",
      slowestCorner: "Turn 13 (80 km/h)",
      longestStraight: "1.3 km",
      pitLaneLength: "350 m",
      lapDistance: "4.304 km",
      raceDistance: "305.354 km (71 laps)",
    },
  },
  {
    id: "interlagos",
    name: "Autódromo José Carlos Pace",
    country: "Brazil",
    countryCode: "br",
    city: "São Paulo",
    length: "4.309 km",
    turns: 15,
    lapRecord: {
      time: "1:10.540",
      driver: "Valtteri Bottas",
      year: 2018,
    },
    firstGrandPrix: 1973,
    coordinates: {
      x: 33.5,
      y: 62.5,
    },
    description:
      "The Autódromo José Carlos Pace, better known as Interlagos, is a motorsport circuit located in the city of São Paulo, Brazil. It is named after Brazilian Formula One driver José Carlos Pace, who died in a plane crash in 1977.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 71,
        time: "1:56:48.894",
      },
      {
        year: 2022,
        winner: "George Russell",
        team: "Mercedes",
        laps: 71,
        time: "1:38:34.044",
      },
      {
        year: 2021,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 71,
        time: "1:32:22.851",
      },
      {
        year: 2019,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 71,
        time: "1:33:14.678",
      },
      {
        year: 2018,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 71,
        time: "1:27:09.066",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Turn 1 (270 km/h)",
      slowestCorner: "Turn 10 (80 km/h)",
      longestStraight: "0.9 km",
      pitLaneLength: "330 m",
      lapDistance: "4.309 km",
      raceDistance: "305.909 km (71 laps)",
    },
  },
  {
    id: "las-vegas",
    name: "Las Vegas Strip Circuit",
    country: "United States",
    countryCode: "us",
    city: "Las Vegas",
    length: "6.120 km",
    turns: 17,
    lapRecord: {
      time: "1:35.490",
      driver: "Oscar Piastri",
      year: 2023,
    },
    firstGrandPrix: 2023,
    coordinates: {
      x: 18.5,
      y: 39.5,
    },
    description:
      "The Las Vegas Strip Circuit is a street circuit in Las Vegas, Nevada. It is the venue for the Las Vegas Grand Prix, which was first held in 2023. The track features a long straight along the famous Las Vegas Strip.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 50,
        time: "1:27:02.144",
      },
    ],
    features: {
      drsZones: 3,
      fastestCorner: "Turn 12 (240 km/h)",
      slowestCorner: "Turn 1 (90 km/h)",
      longestStraight: "1.9 km",
      pitLaneLength: "370 m",
      lapDistance: "6.120 km",
      raceDistance: "305.000 km (50 laps)",
    },
  },
  {
    id: "losail",
    name: "Losail International Circuit",
    country: "Qatar",
    countryCode: "qa",
    city: "Lusail",
    length: "5.380 km",
    turns: 16,
    lapRecord: {
      time: "1:23.196",
      driver: "Max Verstappen",
      year: 2023,
    },
    firstGrandPrix: 2021,
    coordinates: {
      x: 58.5,
      y: 43.5,
    },
    description:
      "The Losail International Circuit is a motorsport race track located just outside the city of Lusail, Qatar. It is the venue for the Qatar Grand Prix, which was first held in 2021.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 57,
        time: "1:27:39.168",
      },
      {
        year: 2021,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 57,
        time: "1:24:28.318",
      },
    ],
    features: {
      drsZones: 3,
      fastestCorner: "Turn 14 (270 km/h)",
      slowestCorner: "Turn 6 (80 km/h)",
      longestStraight: "1.07 km",
      pitLaneLength: "390 m",
      lapDistance: "5.380 km",
      raceDistance: "306.660 km (57 laps)",
    },
  },
  {
    id: "yas-marina",
    name: "Yas Marina Circuit",
    country: "United Arab Emirates",
    countryCode: "ae",
    city: "Abu Dhabi",
    length: "5.281 km",
    turns: 16,
    lapRecord: {
      time: "1:26.103",
      driver: "Max Verstappen",
      year: 2021,
    },
    firstGrandPrix: 2009,
    coordinates: {
      x: 59.5,
      y: 43.5,
    },
    description:
      "The Yas Marina Circuit is a motorsport race track on Yas Island in Abu Dhabi, UAE. It is the venue for the Abu Dhabi Grand Prix. The circuit was designed by Hermann Tilke and is known for its unique features, including a section that runs underneath the Yas Hotel.",
    image: "/placeholder.svg?height=200&width=300",
    history: [
      {
        year: 2023,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 58,
        time: "1:27:02.624",
      },
      {
        year: 2022,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 58,
        time: "1:27:45.714",
      },
      {
        year: 2021,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 58,
        time: "1:30:17.345",
      },
      {
        year: 2020,
        winner: "Max Verstappen",
        team: "Red Bull Racing",
        laps: 55,
        time: "1:36:28.645",
      },
      {
        year: 2019,
        winner: "Lewis Hamilton",
        team: "Mercedes",
        laps: 55,
        time: "1:34:05.715",
      },
    ],
    features: {
      drsZones: 2,
      fastestCorner: "Turn 17 (230 km/h)",
      slowestCorner: "Turn 7 (70 km/h)",
      longestStraight: "1.0 km",
      pitLaneLength: "390 m",
      lapDistance: "5.281 km",
      raceDistance: "306.183 km (58 laps)",
    },
  },
]

export function getAllCircuits(): Circuit[] {
  return circuits
}

export function getCircuitById(id: string): Circuit | undefined {
  return circuits.find((circuit) => circuit.id === id)
}
