export interface Race {
  id: number
  name: string
  circuit: string
  circuitId: string
  location: string
  country: string
  countryCode: string
  date: string
  fullDate: string // YYYY-MM-DD format
  time: string
  round: number
  sprintRace: boolean
  sprintDate?: string
  sprintTime?: string
  qualifyingDate?: string
  qualifyingTime?: string
  practice1Date?: string
  practice1Time?: string
  practice2Date?: string
  practice2Time?: string
  practice3Date?: string
  practice3Time?: string
  daysUntil: number
  isPast: boolean
}

export interface PastRace extends Race {
  results: {
    position: number
    driver: string
    driverId: string
    team: string
    time: string
    points: number
  }[]
  fastestLap: {
    driver: string
    driverId: string
    time: string
    lap: number
  }
  polePosition: {
    driver: string
    driverId: string
    time: string
  }
}

export const races: Race[] = [
  {
    id: 1,
    name: "Bahrain Grand Prix",
    circuit: "Bahrain International Circuit",
    circuitId: "bahrain",
    location: "Sakhir, Bahrain",
    country: "Bahrain",
    countryCode: "bh",
    date: "March 2, 2024",
    fullDate: "2024-03-02",
    time: "16:00",
    round: 1,
    sprintRace: false,
    practice1Date: "2024-03-01",
    practice1Time: "12:30",
    practice2Date: "2024-03-01",
    practice2Time: "16:00",
    practice3Date: "2024-03-02",
    practice3Time: "13:30",
    qualifyingDate: "2024-03-02",
    qualifyingTime: "17:00",
    daysUntil: 0,
    isPast: true,
  },
  {
    id: 2,
    name: "Saudi Arabian Grand Prix",
    circuit: "Jeddah Corniche Circuit",
    circuitId: "jeddah",
    location: "Jeddah, Saudi Arabia",
    country: "Saudi Arabia",
    countryCode: "sa",
    date: "March 9, 2024",
    fullDate: "2024-03-09",
    time: "17:00",
    round: 2,
    sprintRace: false,
    practice1Date: "2024-03-08",
    practice1Time: "13:30",
    practice2Date: "2024-03-08",
    practice2Time: "17:00",
    practice3Date: "2024-03-09",
    practice3Time: "14:30",
    qualifyingDate: "2024-03-09",
    qualifyingTime: "18:00",
    daysUntil: 0,
    isPast: true,
  },
  {
    id: 3,
    name: "Australian Grand Prix",
    circuit: "Albert Park Circuit",
    circuitId: "albert-park",
    location: "Melbourne, Australia",
    country: "Australia",
    countryCode: "au",
    date: "March 24, 2024",
    fullDate: "2024-03-24",
    time: "05:00",
    round: 3,
    sprintRace: false,
    practice1Date: "2024-03-22",
    practice1Time: "01:30",
    practice2Date: "2024-03-22",
    practice2Time: "05:00",
    practice3Date: "2024-03-23",
    practice3Time: "01:30",
    qualifyingDate: "2024-03-23",
    qualifyingTime: "05:00",
    daysUntil: 0,
    isPast: true,
  },
  {
    id: 4,
    name: "Japanese Grand Prix",
    circuit: "Suzuka International Racing Course",
    circuitId: "suzuka",
    location: "Suzuka, Japan",
    country: "Japan",
    countryCode: "jp",
    date: "April 7, 2024",
    fullDate: "2024-04-07",
    time: "06:00",
    round: 4,
    sprintRace: false,
    practice1Date: "2024-04-05",
    practice1Time: "03:30",
    practice2Date: "2024-04-05",
    practice2Time: "07:00",
    practice3Date: "2024-04-06",
    practice3Time: "03:30",
    qualifyingDate: "2024-04-06",
    qualifyingTime: "07:00",
    daysUntil: 0,
    isPast: true,
  },
  {
    id: 5,
    name: "Chinese Grand Prix",
    circuit: "Shanghai International Circuit",
    circuitId: "shanghai",
    location: "Shanghai, China",
    country: "China",
    countryCode: "cn",
    date: "April 21, 2024",
    fullDate: "2024-04-21",
    time: "07:00",
    round: 5,
    sprintRace: true,
    sprintDate: "2024-04-20",
    sprintTime: "04:00",
    practice1Date: "2024-04-19",
    practice1Time: "04:30",
    qualifyingDate: "2024-04-19",
    qualifyingTime: "08:30",
    practice2Date: "2024-04-20",
    practice2Time: "00:30",
    daysUntil: 0,
    isPast: true,
  },
  {
    id: 6,
    name: "Miami Grand Prix",
    circuit: "Miami International Autodrome",
    circuitId: "miami",
    location: "Miami, USA",
    country: "United States",
    countryCode: "us",
    date: "May 5, 2024",
    fullDate: "2024-05-05",
    time: "20:00",
    round: 6,
    sprintRace: true,
    sprintDate: "2024-05-04",
    sprintTime: "17:00",
    practice1Date: "2024-05-03",
    practice1Time: "17:30",
    qualifyingDate: "2024-05-03",
    qualifyingTime: "21:30",
    practice2Date: "2024-05-04",
    practice2Time: "13:30",
    daysUntil: 0,
    isPast: true,
  },
  {
    id: 7,
    name: "Emilia Romagna Grand Prix",
    circuit: "Autodromo Enzo e Dino Ferrari",
    circuitId: "imola",
    location: "Imola, Italy",
    country: "Italy",
    countryCode: "it",
    date: "May 19, 2024",
    fullDate: "2024-05-19",
    time: "14:00",
    round: 7,
    sprintRace: false,
    practice1Date: "2024-05-17",
    practice1Time: "12:30",
    practice2Date: "2024-05-17",
    practice2Time: "16:00",
    practice3Date: "2024-05-18",
    practice3Time: "11:30",
    qualifyingDate: "2024-05-18",
    qualifyingTime: "15:00",
    daysUntil: 0,
    isPast: true,
  },
  {
    id: 8,
    name: "Monaco Grand Prix",
    circuit: "Circuit de Monaco",
    circuitId: "monaco",
    location: "Monte Carlo, Monaco",
    country: "Monaco",
    countryCode: "mc",
    date: "May 26, 2024",
    fullDate: "2024-05-26",
    time: "14:00",
    round: 8,
    sprintRace: false,
    practice1Date: "2024-05-24",
    practice1Time: "12:30",
    practice2Date: "2024-05-24",
    practice2Time: "16:00",
    practice3Date: "2024-05-25",
    practice3Time: "11:30",
    qualifyingDate: "2024-05-25",
    qualifyingTime: "15:00",
    daysUntil: 3,
    isPast: false,
  },
  {
    id: 9,
    name: "Canadian Grand Prix",
    circuit: "Circuit Gilles Villeneuve",
    circuitId: "montreal",
    location: "Montreal, Canada",
    country: "Canada",
    countryCode: "ca",
    date: "June 9, 2024",
    fullDate: "2024-06-09",
    time: "18:00",
    round: 9,
    sprintRace: false,
    practice1Date: "2024-06-07",
    practice1Time: "17:30",
    practice2Date: "2024-06-07",
    practice2Time: "21:00",
    practice3Date: "2024-06-08",
    practice3Time: "16:30",
    qualifyingDate: "2024-06-08",
    qualifyingTime: "20:00",
    daysUntil: 17,
    isPast: false,
  },
  {
    id: 10,
    name: "Spanish Grand Prix",
    circuit: "Circuit de Barcelona-Catalunya",
    circuitId: "barcelona",
    location: "Barcelona, Spain",
    country: "Spain",
    countryCode: "es",
    date: "June 23, 2024",
    fullDate: "2024-06-23",
    time: "14:00",
    round: 10,
    sprintRace: false,
    practice1Date: "2024-06-21",
    practice1Time: "12:30",
    practice2Date: "2024-06-21",
    practice2Time: "16:00",
    practice3Date: "2024-06-22",
    practice3Time: "11:30",
    qualifyingDate: "2024-06-22",
    qualifyingTime: "15:00",
    daysUntil: 31,
    isPast: false,
  },
  {
    id: 11,
    name: "Austrian Grand Prix",
    circuit: "Red Bull Ring",
    circuitId: "spielberg",
    location: "Spielberg, Austria",
    country: "Austria",
    countryCode: "at",
    date: "June 30, 2024",
    fullDate: "2024-06-30",
    time: "14:00",
    round: 11,
    sprintRace: true,
    sprintDate: "2024-06-29",
    sprintTime: "11:00",
    practice1Date: "2024-06-28",
    practice1Time: "12:30",
    qualifyingDate: "2024-06-28",
    qualifyingTime: "16:30",
    practice2Date: "2024-06-29",
    practice2Time: "08:30",
    daysUntil: 38,
    isPast: false,
  },
  {
    id: 12,
    name: "British Grand Prix",
    circuit: "Silverstone Circuit",
    circuitId: "silverstone",
    location: "Silverstone, UK",
    country: "United Kingdom",
    countryCode: "gb",
    date: "July 7, 2024",
    fullDate: "2024-07-07",
    time: "15:00",
    round: 12,
    sprintRace: false,
    practice1Date: "2024-07-05",
    practice1Time: "12:30",
    practice2Date: "2024-07-05",
    practice2Time: "16:00",
    practice3Date: "2024-07-06",
    practice3Time: "11:30",
    qualifyingDate: "2024-07-06",
    qualifyingTime: "15:00",
    daysUntil: 45,
    isPast: false,
  },
]

export const pastRaces: PastRace[] = [
  {
    id: 1,
    name: "Bahrain Grand Prix",
    circuit: "Bahrain International Circuit",
    circuitId: "bahrain",
    location: "Sakhir, Bahrain",
    country: "Bahrain",
    countryCode: "bh",
    date: "March 2, 2024",
    fullDate: "2024-03-02",
    time: "16:00",
    round: 1,
    sprintRace: false,
    practice1Date: "2024-03-01",
    practice1Time: "12:30",
    practice2Date: "2024-03-01",
    practice2Time: "16:00",
    practice3Date: "2024-03-02",
    practice3Time: "13:30",
    qualifyingDate: "2024-03-02",
    qualifyingTime: "17:00",
    daysUntil: 0,
    isPast: true,
    results: [
      {
        position: 1,
        driver: "Max Verstappen",
        driverId: "max-verstappen",
        team: "Red Bull Racing",
        time: "1:31:44.742",
        points: 25,
      },
      {
        position: 2,
        driver: "Sergio Perez",
        driverId: "sergio-perez",
        team: "Red Bull Racing",
        time: "+2.223s",
        points: 18,
      },
      { position: 3, driver: "Carlos Sainz", driverId: "carlos-sainz", team: "Ferrari", time: "+8.651s", points: 15 },
      {
        position: 4,
        driver: "Charles Leclerc",
        driverId: "charles-leclerc",
        team: "Ferrari",
        time: "+10.222s",
        points: 12,
      },
      {
        position: 5,
        driver: "George Russell",
        driverId: "george-russell",
        team: "Mercedes",
        time: "+42.250s",
        points: 10,
      },
    ],
    fastestLap: {
      driver: "Max Verstappen",
      driverId: "max-verstappen",
      time: "1:32.608",
      lap: 40,
    },
    polePosition: {
      driver: "Max Verstappen",
      driverId: "max-verstappen",
      time: "1:29.179",
    },
  },
  {
    id: 2,
    name: "Saudi Arabian Grand Prix",
    circuit: "Jeddah Corniche Circuit",
    circuitId: "jeddah",
    location: "Jeddah, Saudi Arabia",
    country: "Saudi Arabia",
    countryCode: "sa",
    date: "March 9, 2024",
    fullDate: "2024-03-09",
    time: "17:00",
    round: 2,
    sprintRace: false,
    practice1Date: "2024-03-08",
    practice1Time: "13:30",
    practice2Date: "2024-03-08",
    practice2Time: "17:00",
    practice3Date: "2024-03-09",
    practice3Time: "14:30",
    qualifyingDate: "2024-03-09",
    qualifyingTime: "18:00",
    daysUntil: 0,
    isPast: true,
    results: [
      {
        position: 1,
        driver: "Max Verstappen",
        driverId: "max-verstappen",
        team: "Red Bull Racing",
        time: "1:20:43.273",
        points: 25,
      },
      {
        position: 2,
        driver: "Sergio Perez",
        driverId: "sergio-perez",
        team: "Red Bull Racing",
        time: "+13.643s",
        points: 18,
      },
      {
        position: 3,
        driver: "Charles Leclerc",
        driverId: "charles-leclerc",
        team: "Ferrari",
        time: "+18.639s",
        points: 16,
      },
      {
        position: 4,
        driver: "Oscar Piastri",
        driverId: "oscar-piastri",
        team: "McLaren",
        time: "+34.759s",
        points: 12,
      },
      {
        position: 5,
        driver: "Fernando Alonso",
        driverId: "fernando-alonso",
        team: "Aston Martin",
        time: "+43.571s",
        points: 10,
      },
    ],
    fastestLap: {
      driver: "Charles Leclerc",
      driverId: "charles-leclerc",
      time: "1:31.632",
      lap: 50,
    },
    polePosition: {
      driver: "Max Verstappen",
      driverId: "max-verstappen",
      time: "1:28.197",
    },
  },
  {
    id: 3,
    name: "Australian Grand Prix",
    circuit: "Albert Park Circuit",
    circuitId: "albert-park",
    location: "Melbourne, Australia",
    country: "Australia",
    countryCode: "au",
    date: "March 24, 2024",
    fullDate: "2024-03-24",
    time: "05:00",
    round: 3,
    sprintRace: false,
    practice1Date: "2024-03-22",
    practice1Time: "01:30",
    practice2Date: "2024-03-22",
    practice2Time: "05:00",
    practice3Date: "2024-03-23",
    practice3Time: "01:30",
    qualifyingDate: "2024-03-23",
    qualifyingTime: "05:00",
    daysUntil: 0,
    isPast: true,
    results: [
      {
        position: 1,
        driver: "Carlos Sainz",
        driverId: "carlos-sainz",
        team: "Ferrari",
        time: "1:15:28.97",
        points: 25,
      },
      {
        position: 2,
        driver: "Charles Leclerc",
        driverId: "charles-leclerc",
        team: "Ferrari",
        time: "+2.366s",
        points: 18,
      },
      { position: 3, driver: "Lando Norris", driverId: "lando-norris", team: "McLaren", time: "+5.904s", points: 15 },
      {
        position: 4,
        driver: "Oscar Piastri",
        driverId: "oscar-piastri",
        team: "McLaren",
        time: "+35.770s",
        points: 12,
      },
      {
        position: 5,
        driver: "Sergio Perez",
        driverId: "sergio-perez",
        team: "Red Bull Racing",
        time: "+56.309s",
        points: 10,
      },
    ],
    fastestLap: {
      driver: "Lando Norris",
      driverId: "lando-norris",
      time: "1:19.813",
      lap: 57,
    },
    polePosition: {
      driver: "Max Verstappen",
      driverId: "max-verstappen",
      time: "1:15.915",
    },
  },
  {
    id: 4,
    name: "Japanese Grand Prix",
    circuit: "Suzuka International Racing Course",
    circuitId: "suzuka",
    location: "Suzuka, Japan",
    country: "Japan",
    countryCode: "jp",
    date: "April 7, 2024",
    fullDate: "2024-04-07",
    time: "06:00",
    round: 4,
    sprintRace: false,
    practice1Date: "2024-04-05",
    practice1Time: "03:30",
    practice2Date: "2024-04-05",
    practice2Time: "07:00",
    practice3Date: "2024-04-06",
    practice3Time: "03:30",
    qualifyingDate: "2024-04-06",
    qualifyingTime: "07:00",
    daysUntil: 0,
    isPast: true,
    results: [
      {
        position: 1,
        driver: "Max Verstappen",
        driverId: "max-verstappen",
        team: "Red Bull Racing",
        time: "1:30:58.421",
        points: 25,
      },
      {
        position: 2,
        driver: "Sergio Perez",
        driverId: "sergio-perez",
        team: "Red Bull Racing",
        time: "+12.535s",
        points: 18,
      },
      { position: 3, driver: "Carlos Sainz", driverId: "carlos-sainz", team: "Ferrari", time: "+20.866s", points: 15 },
      {
        position: 4,
        driver: "Charles Leclerc",
        driverId: "charles-leclerc",
        team: "Ferrari",
        time: "+26.522s",
        points: 12,
      },
      { position: 5, driver: "Lando Norris", driverId: "lando-norris", team: "McLaren", time: "+29.418s", points: 10 },
    ],
    fastestLap: {
      driver: "Max Verstappen",
      driverId: "max-verstappen",
      time: "1:33.706",
      lap: 33,
    },
    polePosition: {
      driver: "Max Verstappen",
      driverId: "max-verstappen",
      time: "1:28.197",
    },
  },
  {
    id: 5,
    name: "Chinese Grand Prix",
    circuit: "Shanghai International Circuit",
    circuitId: "shanghai",
    location: "Shanghai, China",
    country: "China",
    countryCode: "cn",
    date: "April 21, 2024",
    fullDate: "2024-04-21",
    time: "07:00",
    round: 5,
    sprintRace: true,
    sprintDate: "2024-04-20",
    sprintTime: "04:00",
    practice1Date: "2024-04-19",
    practice1Time: "04:30",
    qualifyingDate: "2024-04-19",
    qualifyingTime: "08:30",
    practice2Date: "2024-04-20",
    practice2Time: "00:30",
    daysUntil: 0,
    isPast: true,
    results: [
      {
        position: 1,
        driver: "Max Verstappen",
        driverId: "max-verstappen",
        team: "Red Bull Racing",
        time: "1:40:52.554",
        points: 25,
      },
      { position: 2, driver: "Lando Norris", driverId: "lando-norris", team: "McLaren", time: "+13.773s", points: 18 },
      {
        position: 3,
        driver: "Sergio Perez",
        driverId: "sergio-perez",
        team: "Red Bull Racing",
        time: "+19.160s",
        points: 15,
      },
      {
        position: 4,
        driver: "Charles Leclerc",
        driverId: "charles-leclerc",
        team: "Ferrari",
        time: "+23.623s",
        points: 12,
      },
      { position: 5, driver: "Carlos Sainz", driverId: "carlos-sainz", team: "Ferrari", time: "+33.983s", points: 10 },
    ],
    fastestLap: {
      driver: "Max Verstappen",
      driverId: "max-verstappen",
      time: "1:37.810",
      lap: 55,
    },
    polePosition: {
      driver: "Max Verstappen",
      driverId: "max-verstappen",
      time: "1:34.970",
    },
  },
  {
    id: 6,
    name: "Miami Grand Prix",
    circuit: "Miami International Autodrome",
    circuitId: "miami",
    location: "Miami, USA",
    country: "United States",
    countryCode: "us",
    date: "May 5, 2024",
    fullDate: "2024-05-05",
    time: "20:00",
    round: 6,
    sprintRace: true,
    sprintDate: "2024-05-04",
    sprintTime: "17:00",
    practice1Date: "2024-05-03",
    practice1Time: "17:30",
    qualifyingDate: "2024-05-03",
    qualifyingTime: "21:30",
    practice2Date: "2024-05-04",
    practice2Time: "13:30",
    daysUntil: 0,
    isPast: true,
    results: [
      {
        position: 1,
        driver: "Lando Norris",
        driverId: "lando-norris",
        team: "McLaren",
        time: "1:30:49.876",
        points: 25,
      },
      {
        position: 2,
        driver: "Max Verstappen",
        driverId: "max-verstappen",
        team: "Red Bull Racing",
        time: "+7.612s",
        points: 18,
      },
      {
        position: 3,
        driver: "Charles Leclerc",
        driverId: "charles-leclerc",
        team: "Ferrari",
        time: "+9.920s",
        points: 15,
      },
      {
        position: 4,
        driver: "Sergio Perez",
        driverId: "sergio-perez",
        team: "Red Bull Racing",
        time: "+14.650s",
        points: 12,
      },
      { position: 5, driver: "Carlos Sainz", driverId: "carlos-sainz", team: "Ferrari", time: "+16.407s", points: 10 },
    ],
    fastestLap: {
      driver: "Lando Norris",
      driverId: "lando-norris",
      time: "1:30.257",
      lap: 56,
    },
    polePosition: {
      driver: "Max Verstappen",
      driverId: "max-verstappen",
      time: "1:29.879",
    },
  },
  {
    id: 7,
    name: "Emilia Romagna Grand Prix",
    circuit: "Autodromo Enzo e Dino Ferrari",
    circuitId: "imola",
    location: "Imola, Italy",
    country: "Italy",
    countryCode: "it",
    date: "May 19, 2024",
    fullDate: "2024-05-19",
    time: "14:00",
    round: 7,
    sprintRace: false,
    practice1Date: "2024-05-17",
    practice1Time: "12:30",
    practice2Date: "2024-05-17",
    practice2Time: "16:00",
    practice3Date: "2024-05-18",
    practice3Time: "11:30",
    qualifyingDate: "2024-05-18",
    qualifyingTime: "15:00",
    daysUntil: 0,
    isPast: true,
    results: [
      {
        position: 1,
        driver: "Max Verstappen",
        driverId: "max-verstappen",
        team: "Red Bull Racing",
        time: "1:25:25.252",
        points: 25,
      },
      { position: 2, driver: "Lando Norris", driverId: "lando-norris", team: "McLaren", time: "+0.725s", points: 18 },
      {
        position: 3,
        driver: "Charles Leclerc",
        driverId: "charles-leclerc",
        team: "Ferrari",
        time: "+7.916s",
        points: 15,
      },
      {
        position: 4,
        driver: "Oscar Piastri",
        driverId: "oscar-piastri",
        team: "McLaren",
        time: "+14.132s",
        points: 12,
      },
      { position: 5, driver: "Carlos Sainz", driverId: "carlos-sainz", team: "Ferrari", time: "+22.325s", points: 10 },
    ],
    fastestLap: {
      driver: "Lewis Hamilton",
      driverId: "lewis-hamilton",
      time: "1:19.060",
      lap: 63,
    },
    polePosition: {
      driver: "Max Verstappen",
      driverId: "max-verstappen",
      time: "1:14.746",
    },
  },
]

export function getNextRace(): Race | undefined {
  const now = new Date()

  // Find the first race that hasn't happened yet
  return races.find((race) => {
    const [year, month, day] = race.fullDate.split("-").map(Number)
    const raceDate = new Date(year, month - 1, day)
    return raceDate > now
  })
}

export function getPreviousRace(): PastRace | undefined {
  // Return the most recent past race
  return pastRaces[pastRaces.length - 1]
}
