export const races = [
  {
    id: 1,
    name: "Bahrain Grand Prix",
    circuit: "Bahrain International Circuit",
    location: "Sakhir, Bahrain",
    date: "March 2, 2024",
    time: "16:00 GMT",
    round: 1,
    sprintRace: false,
    daysUntil: 0, // Past race
  },
  {
    id: 2,
    name: "Saudi Arabian Grand Prix",
    circuit: "Jeddah Corniche Circuit",
    location: "Jeddah, Saudi Arabia",
    date: "March 9, 2024",
    time: "17:00 GMT",
    round: 2,
    sprintRace: false,
    daysUntil: 0, // Past race
  },
  {
    id: 3,
    name: "Australian Grand Prix",
    circuit: "Albert Park Circuit",
    location: "Melbourne, Australia",
    date: "March 24, 2024",
    time: "05:00 GMT",
    round: 3,
    sprintRace: false,
    daysUntil: 0, // Past race
  },
  {
    id: 4,
    name: "Japanese Grand Prix",
    circuit: "Suzuka International Racing Course",
    location: "Suzuka, Japan",
    date: "April 7, 2024",
    time: "06:00 GMT",
    round: 4,
    sprintRace: false,
    daysUntil: 0, // Past race
  },
  {
    id: 5,
    name: "Chinese Grand Prix",
    circuit: "Shanghai International Circuit",
    location: "Shanghai, China",
    date: "April 21, 2024",
    time: "07:00 GMT",
    round: 5,
    sprintRace: true,
    daysUntil: 0, // Past race
  },
  {
    id: 6,
    name: "Miami Grand Prix",
    circuit: "Miami International Autodrome",
    location: "Miami, USA",
    date: "May 5, 2024",
    time: "20:00 GMT",
    round: 6,
    sprintRace: true,
    daysUntil: 0, // Past race
  },
  {
    id: 7,
    name: "Emilia Romagna Grand Prix",
    circuit: "Autodromo Enzo e Dino Ferrari",
    location: "Imola, Italy",
    date: "May 19, 2024",
    time: "14:00 GMT",
    round: 7,
    sprintRace: false,
    daysUntil: 0, // Past race
  },
  {
    id: 8,
    name: "Monaco Grand Prix",
    circuit: "Circuit de Monaco",
    location: "Monte Carlo, Monaco",
    date: "May 26, 2024",
    time: "14:00 GMT",
    round: 8,
    sprintRace: false,
    daysUntil: 3, // Upcoming race
  },
  {
    id: 9,
    name: "Canadian Grand Prix",
    circuit: "Circuit Gilles Villeneuve",
    location: "Montreal, Canada",
    date: "June 9, 2024",
    time: "18:00 GMT",
    round: 9,
    sprintRace: false,
    daysUntil: 17,
  },
  {
    id: 10,
    name: "Spanish Grand Prix",
    circuit: "Circuit de Barcelona-Catalunya",
    location: "Barcelona, Spain",
    date: "June 23, 2024",
    time: "14:00 GMT",
    round: 10,
    sprintRace: false,
    daysUntil: 31,
  },
  {
    id: 11,
    name: "Austrian Grand Prix",
    circuit: "Red Bull Ring",
    location: "Spielberg, Austria",
    date: "June 30, 2024",
    time: "14:00 GMT",
    round: 11,
    sprintRace: true,
    daysUntil: 38,
  },
  {
    id: 12,
    name: "British Grand Prix",
    circuit: "Silverstone Circuit",
    location: "Silverstone, UK",
    date: "July 7, 2024",
    time: "15:00 GMT",
    round: 12,
    sprintRace: false,
    daysUntil: 45,
  },
]

export const pastRaces = [
  {
    id: 1,
    name: "Bahrain Grand Prix",
    circuit: "Bahrain International Circuit",
    location: "Sakhir, Bahrain",
    date: "March 2, 2024",
    round: 1,
    results: [
      { position: 1, driver: "Max Verstappen", time: "1:31:44.742" },
      { position: 2, driver: "Sergio Perez", time: "+2.223s" },
      { position: 3, driver: "Carlos Sainz", time: "+8.651s" },
    ],
    fastestLap: {
      driver: "Max Verstappen",
      time: "1:32.608",
    },
  },
  {
    id: 2,
    name: "Saudi Arabian Grand Prix",
    circuit: "Jeddah Corniche Circuit",
    location: "Jeddah, Saudi Arabia",
    date: "March 9, 2024",
    round: 2,
    results: [
      { position: 1, driver: "Max Verstappen", time: "1:20:43.273" },
      { position: 2, driver: "Sergio Perez", time: "+13.643s" },
      { position: 3, driver: "Charles Leclerc", time: "+18.639s" },
    ],
    fastestLap: {
      driver: "Charles Leclerc",
      time: "1:31.632",
    },
  },
  {
    id: 3,
    name: "Australian Grand Prix",
    circuit: "Albert Park Circuit",
    location: "Melbourne, Australia",
    date: "March 24, 2024",
    round: 3,
    results: [
      { position: 1, driver: "Carlos Sainz", time: "1:15:28.97" },
      { position: 2, driver: "Charles Leclerc", time: "+2.366s" },
      { position: 3, driver: "Lando Norris", time: "+5.904s" },
    ],
    fastestLap: {
      driver: "Lando Norris",
      time: "1:19.813",
    },
  },
  {
    id: 4,
    name: "Japanese Grand Prix",
    circuit: "Suzuka International Racing Course",
    location: "Suzuka, Japan",
    date: "April 7, 2024",
    round: 4,
    results: [
      { position: 1, driver: "Max Verstappen", time: "1:30:58.421" },
      { position: 2, driver: "Sergio Perez", time: "+12.535s" },
      { position: 3, driver: "Carlos Sainz", time: "+20.866s" },
    ],
    fastestLap: {
      driver: "Max Verstappen",
      time: "1:33.706",
    },
  },
  {
    id: 5,
    name: "Chinese Grand Prix",
    circuit: "Shanghai International Circuit",
    location: "Shanghai, China",
    date: "April 21, 2024",
    round: 5,
    results: [
      { position: 1, driver: "Max Verstappen", time: "1:40:52.554" },
      { position: 2, driver: "Lando Norris", time: "+13.773s" },
      { position: 3, driver: "Sergio Perez", time: "+19.160s" },
    ],
    fastestLap: {
      driver: "Max Verstappen",
      time: "1:37.810",
    },
  },
  {
    id: 6,
    name: "Miami Grand Prix",
    circuit: "Miami International Autodrome",
    location: "Miami, USA",
    date: "May 5, 2024",
    round: 6,
    results: [
      { position: 1, driver: "Lando Norris", time: "1:30:49.876" },
      { position: 2, driver: "Max Verstappen", time: "+7.612s" },
      { position: 3, driver: "Charles Leclerc", time: "+9.920s" },
    ],
    fastestLap: {
      driver: "Lando Norris",
      time: "1:30.257",
    },
  },
  {
    id: 7,
    name: "Emilia Romagna Grand Prix",
    circuit: "Autodromo Enzo e Dino Ferrari",
    location: "Imola, Italy",
    date: "May 19, 2024",
    round: 7,
    results: [
      { position: 1, driver: "Max Verstappen", time: "1:25:25.252" },
      { position: 2, driver: "Lando Norris", time: "+0.725s" },
      { position: 3, driver: "Charles Leclerc", time: "+7.916s" },
    ],
    fastestLap: {
      driver: "Lewis Hamilton",
      time: "1:19.060",
    },
  },
]
