export interface TeamRadioMessage {
  id: string
  raceId: number
  timestamp: string // Format: "HH:MM:SS"
  lap: number
  driver: string
  driverId: string
  team: string
  message: string
  audioUrl?: string
}

export const teamRadioMessages: TeamRadioMessage[] = [
  {
    id: "tr-7-1",
    raceId: 7,
    timestamp: "14:15:23",
    lap: 1,
    driver: "Max Verstappen",
    driverId: "max-verstappen",
    team: "Red Bull Racing",
    message: "Good start, gap to P2 is 0.8 seconds.",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-7-2",
    raceId: 7,
    timestamp: "14:17:45",
    lap: 3,
    driver: "Charles Leclerc",
    driverId: "charles-leclerc",
    team: "Ferrari",
    message: "How's the pace compared to Verstappen? Can we catch him?",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-7-3",
    raceId: 7,
    timestamp: "14:20:12",
    lap: 5,
    driver: "Lando Norris",
    driverId: "lando-norris",
    team: "McLaren",
    message: "Car feels good, I think we can push more on the straights.",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-7-4",
    raceId: 7,
    timestamp: "14:25:37",
    lap: 10,
    driver: "Max Verstappen",
    driverId: "max-verstappen",
    team: "Red Bull Racing",
    message: "Tires are starting to drop off a bit in the high-speed corners.",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-7-5",
    raceId: 7,
    timestamp: "14:30:45",
    lap: 15,
    driver: "Charles Leclerc",
    driverId: "charles-leclerc",
    team: "Ferrari",
    message: "Box this lap, box this lap. Confirm.",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-7-6",
    raceId: 7,
    timestamp: "14:45:18",
    lap: 30,
    driver: "Lewis Hamilton",
    driverId: "lewis-hamilton",
    team: "Mercedes",
    message: "The car is much better on these tires, we should have pitted earlier.",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-7-7",
    raceId: 7,
    timestamp: "15:00:22",
    lap: 45,
    driver: "Max Verstappen",
    driverId: "max-verstappen",
    team: "Red Bull Racing",
    message: "How many laps to go? The rear is starting to slide a bit.",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-7-8",
    raceId: 7,
    timestamp: "15:15:05",
    lap: 60,
    driver: "Lando Norris",
    driverId: "lando-norris",
    team: "McLaren",
    message: "Can we get the fastest lap? What time do I need?",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-7-9",
    raceId: 7,
    timestamp: "15:18:30",
    lap: 63,
    driver: "Max Verstappen",
    driverId: "max-verstappen",
    team: "Red Bull Racing",
    message: "Yes! Great job team, perfect strategy today. Thank you!",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-6-1",
    raceId: 6,
    timestamp: "20:05:23",
    lap: 1,
    driver: "Max Verstappen",
    driverId: "max-verstappen",
    team: "Red Bull Racing",
    message: "Lost position at the start, car doesn't feel great.",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-6-2",
    raceId: 6,
    timestamp: "20:10:45",
    lap: 5,
    driver: "Lando Norris",
    driverId: "lando-norris",
    team: "McLaren",
    message: "The pace is really good, I think we can catch the Ferraris.",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-6-3",
    raceId: 6,
    timestamp: "20:15:12",
    lap: 10,
    driver: "Charles Leclerc",
    driverId: "charles-leclerc",
    team: "Ferrari",
    message: "How's my pace compared to Norris? He seems to be getting closer.",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-6-4",
    raceId: 6,
    timestamp: "20:25:37",
    lap: 20,
    driver: "Lando Norris",
    driverId: "lando-norris",
    team: "McLaren",
    message: "I've got the lead! Car feels amazing, let's keep pushing!",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-6-5",
    raceId: 6,
    timestamp: "20:35:45",
    lap: 30,
    driver: "Max Verstappen",
    driverId: "max-verstappen",
    team: "Red Bull Racing",
    message: "How far ahead is Norris? Can we catch him?",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-6-6",
    raceId: 6,
    timestamp: "20:45:18",
    lap: 40,
    driver: "Charles Leclerc",
    driverId: "charles-leclerc",
    team: "Ferrari",
    message: "Tires are holding up well, I think we can maintain this pace to the end.",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-6-7",
    raceId: 6,
    timestamp: "20:55:22",
    lap: 50,
    driver: "Lando Norris",
    driverId: "lando-norris",
    team: "McLaren",
    message: "How many laps to go? Just need to bring it home now.",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
  {
    id: "tr-6-8",
    raceId: 6,
    timestamp: "21:00:05",
    lap: 57,
    driver: "Lando Norris",
    driverId: "lando-norris",
    team: "McLaren",
    message: "YES! First win! Thank you everyone, the car was incredible today!",
    audioUrl: "/audio/team-radio-sample.mp3",
  },
]

export function getTeamRadioByRace(raceId: number): TeamRadioMessage[] {
  return teamRadioMessages.filter((message) => message.raceId === raceId)
}
